export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  REPUBLIC_ADMIN: 'REPUBLIC_ADMIN',
  REGION_ADMIN: 'REGION_ADMIN',
  DISTRICT_ADMIN: 'DISTRICT_ADMIN',
  MAHALLA_LEADER: 'MAHALLA_LEADER',
  YOUTH: 'YOUTH',
  MODERATOR: 'MODERATOR',
} as const;

export const ADMIN_ROLES = [
  ROLES.SUPER_ADMIN,
  ROLES.REPUBLIC_ADMIN,
  ROLES.REGION_ADMIN,
  ROLES.DISTRICT_ADMIN,
  ROLES.MAHALLA_LEADER,
  ROLES.MODERATOR,
];

export const APPEAL_CATEGORIES = [
  'EMPLOYMENT',
  'EDUCATION',
  'CREDIT',
  'HOUSING',
  'HEALTHCARE',
  'SPORT',
  'CULTURE',
  'LEGAL',
  'SOCIAL',
  'OTHER',
] as const;

export const APPEAL_STATUSES = {
  NEW: 'NEW',
  IN_PROGRESS: 'IN_PROGRESS',
  RESOLVED: 'RESOLVED',
  REJECTED: 'REJECTED',
  CLOSED: 'CLOSED',
} as const;

export const TASK_STATUSES = {
  TODO: 'TODO',
  IN_PROGRESS: 'IN_PROGRESS',
  DONE: 'DONE',
  CANCELLED: 'CANCELLED',
} as const;

export const PROBLEM_STATUSES = {
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED',
} as const;

export const GENDERS = ['MALE', 'FEMALE'] as const;

export const EDUCATION_LEVELS = [
  'NONE', 'SECONDARY', 'VOCATIONAL', 'HIGHER', 'MASTERS', 'PHD',
] as const;

export const EMPLOYMENT_STATUSES = [
  'EMPLOYED', 'UNEMPLOYED', 'STUDENT', 'SELF_EMPLOYED', 'OTHER',
] as const;

export const SOCIAL_STATUSES = [
  'NORMAL', 'ORPHAN', 'DISABLED', 'LOW_INCOME', 'SINGLE_PARENT', 'OTHER',
] as const;

export const RISK_LEVELS = ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'] as const;

export const PRIORITIES = ['LOW', 'MEDIUM', 'HIGH', 'URGENT'] as const;

export const PROBLEM_CATEGORIES = [
  'INFRASTRUCTURE', 'SOCIAL', 'EDUCATION', 'HEALTHCARE',
  'EMPLOYMENT', 'ENVIRONMENT', 'SECURITY', 'OTHER',
] as const;

export const BROADCAST_TARGETS = ['ALL', 'ROLE', 'REGION', 'DISTRICT', 'MAHALLA'] as const;
